### ISSUE TITLE
Search questions with Relevanssi plugin

### ISSUE THREAD

**Issue by shadowshades** [anspress/anspress#324]
Hello,
I've just installed Relevanssi plugin to get relevent search results while searching questions and answers. But it always return any result. Any idea ?
Thank you!

**Comment by bmackinney** [comment]
We've had sucess with https://wordpress.org/plugins/search-autocomplete/

**Comment by shadowshades** [comment]
The search-autocomplete plugin only implements the jQuery UI Autocomplete functionality, it do not replaces the default search results with a partial-match search that sorts results by relevance. I think it still an issue.

**Comment by dima-stefantsov** [comment]
"But it always return any result. Any idea ?"
It's not clear for me what you wanted to say.

You are not getting any results? That's because you have "Respect exclude_from_search for custom post types" checked in Relevanssi. Uncheck it, choose custom post types question and answer, and it will be found.

Titles may duplicate, though.
